name: Self-hosted runner (past-ci-caller)

on:
  push:
    branches:
      - run-past-ci*

jobs:
  run_past_ci_pytorch_1-4:
    name: PyTorch 1.4
    if: always()
    uses: ./.github/workflows/self-past.yml
    with:
      framework: pytorch
      version: "1.4"
    secrets: inherit

  run_past_ci_tensorflow_2-4:
    name: TensorFlow 2.4
    if: always()
    needs: [run_past_ci_pytorch_1-4]
    uses: ./.github/workflows/self-past.yml
    with:
      framework: tensorflow
      version: "2.4"
    secrets: inherit